# Generated by Django 5.2.8 on 2025-11-15 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'albumns',
            },
        ),
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
                ('albumId', models.ForeignKey(db_column='albumn_id', on_delete=django.db.models.deletion.RESTRICT, related_name='recuerdos', to='gestion.album')),
            ],
            options={
                'db_table': 'recuerdos',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(unique=True)),
                ('path', models.TextField()),
                ('extension', models.TextField()),
                ('contentType', models.TextField(db_column='content_type')),
                ('recuerdoId', models.ForeignKey(db_column='recuerdo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='archivos', to='gestion.recuerdo')),
            ],
            options={
                'db_table': 'archivos',
            },
        ),
    ]
