# Generated by Django 5.2.8 on 2025-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creacion_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
