"""agregue tabla multimedia

Revision ID: 568520741992
Revises: da54890bda20
Create Date: 2025-10-25 11:07:45.883279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568520741992'
down_revision = 'da54890bda20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multimedias')
    # ### end Alembic commands ###
