# Generated by Django 5.2.8 on 2025-11-08 15:50

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', django_ulid.models.ULIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', django_ulid.models.ULIDField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('autor', models.TextField()),
                ('edicion', models.TextField()),
                ('descripcion', models.TextField()),
                ('categoriaId', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='gestion.categoria')),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', django_ulid.models.ULIDField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.TextField()),
                ('libroId', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='gestion.libro')),
                ('usuarioId', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='librosPrestadosUsuarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
