# Generated by Django 5.2.8 on 2025-11-09 14:54

import django_ulid.models
import ulid.api.api
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creacion_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
    ]
