# Generated by Django 5.2.8 on 2025-11-09 16:19

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_modificacion_columnas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.TextField(choices=[('1', 'ADMIN'), ('2', 'USUARIO'), ('3', 'PERSONAL')], db_column='tipo_usuario', default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, primary_key=True, serialize=False),
        ),
    ]
