"""cambie tipo de datos y nombre a columna llamada orden

Revision ID: 2dde7686f695
Revises: a330fd9bcfe0
Create Date: 2025-10-04 09:54:44.435683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dde7686f695'
down_revision = 'a330fd9bcfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('orden', new_column_name='posicion',
                              existing_type=sa.INTEGER(), type_=sa.Float())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('posicion', new_column_name='orden',
                              existing_type=sa.Float(), type_=sa.INTEGER())
    # ### end Alembic commands ###
